version: '3'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  server:
    build: ./server
    ports:
      - '5001:5000' # Changed to port 5001
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/andromeda_db
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'